### ISSUE TITLE
World Locking is Incompatible with Extended Eye Tracking

### ISSUE THREAD

**Issue by jackmca** [microsoft/MixedReality-EyeTracking-Sample#1]
**Describe the bug**
Scripts based on the code supplied in this repository work well in my project, however once I scan a QR code (and initiate World Locking), all eye gaze data becomes incorrect.

I have tried using World Space eye gaze data and I have also tried using Camera Space eye gaze data as my thinking is that this would adjust with World Locking along with the Main Camera, however both methods were fruitless.

**To Reproduce**
1. Follow the setup instructions for this repository
2. Import World Locking Tools
3. Setup a basic QR code that utilises Work Locking when scanned
4. Observe how scanning a QR code (initiating World Locking) causes all eye gaze data to become incorrect

**Expected behavior**
Extended Eye Tracking should still function even after initiating World Locking.

**Environment**
- Unity version: 2020.3.41
- Mixed Reality OpenXR Plugin version: 1.4.0
- Mixed Reality Toolkit version: 2.7.3.0
- HoloLens 2

**Additional context**
Standard MRTK eye gaze works regardless of world locking, so I'm trying to figure out what is different in EET, as I would prefer to use EET than the standard eye tracking supplied in MRTK.

Apologies if this is the wrong area to submit issues with EET, as I could not find a more suitable area.

**Comment by Bowen-MS** [comment]
Thanks for the report. 

According to the [document of WLT](https://learn.microsoft.com/en-us/mixed-reality/world-locking-tools/documentation/concepts/basicconcepts#camera-movement-implications), the head coordinates are explained under the "frozen" space, while the extended eye tracking data is finally explained under the "spongy" space, which is the coordinate space before applying WLT's correction. This leads the relative pose of eye gaze and head incorrect. 

MRTK has already factored in the need for such transforms, so the standard MRTK eye gaze works fine there. 

We will work to make this extended eye tracking data also compatible with WLT.

**Comment by Bowen-MS** [comment]
We have updated the content of `ExtendedEyeGazeDataProvider.cs`, (#2) and it should work with WLT now.

**Comment by jackmca** [comment]
Thank you, will give it a try!
